### ISSUE TITLE
Ain't solving, I typed pwd(/home/trencer/genomics/sample_data) but still I get the same issue sir

### ISSUE THREAD

**Issue by pritishmahi811** [GomathiNayagam/genomics#1]
$ spades -1 short_reads_1.fastq.gz -2 short_reads_2.fastq.gz -o /home/trencer@Mahi:/assembly/
Traceback (most recent call last):
  File "/usr/lib/spades/bin/spades.py", line 1122, in <module>
    main(sys.argv)
  File "/usr/lib/spades/bin/spades.py", line 671, in main
    cfg, dataset_data = fill_cfg(options, log)
  File "/usr/lib/spades/bin/spades.py", line 393, in fill_cfg
    os.makedirs(options_storage.output_dir)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/trencer@Mahi:'

**Comment by GomathiNayagam** [comment]
You could try with sudo, but i wouldn't recommend it. 
sudo spades -1 short_reads_1.fastq.gz -2 short_reads_2.fastq.gz -o /home/trencer@Mahi:/assembly/.
My recommendation is, try the following command,
spades -1 short_reads_1.fastq.gz -2 short_reads_2.fastq.gz -o /home/trencer/assembly/

(or)

sudo spades -1 short_reads_1.fastq.gz -2 short_reads_2.fastq.gz -o /assembly/

then later you could look for assembly folder by typing, whereis assembly

**Comment by GomathiNayagam** [comment]
Idle
