### ISSUE TITLE
NGS workshop regarding

### ISSUE THREAD

**Issue by Merlinsobia** [GomathiNayagam/genomics#3]
Hello Sir,
Merlin here. i have the doubt regarding commands. can you please give some notes for commands and getting genome depository. yesterday i understood that we created a directory and upload raw data there. but again i tried to open that fasta format, i forgot the command. so kindly give some notes for commands i.e., as we are beginners. Thank you

**Comment by GomathiNayagam** [comment]
Hi Merlin,
cd scsb/genomics/sample_data
try this command to get to the fasta files.
use less PAM.contigs.fasta to visualise.
I will again refresh it on the next session.

**Comment by Merlinsobia** [comment]
Thank you. can able to visualize it. 
regarding assignment, should we just go through that spade document?? bz it contains lot of information which is tough too for understanding!.

**Comment by GomathiNayagam** [comment]
You see only how assembly works. Need not study the entire data. I will
explain things in the next session.
S.Gomathi Nayagam.
